### PR TITLE
Fix light theme

### PR DESCRIPTION
**Pull request by JoshHyde9**
Dark: 
image

Light: 
image

### CODE REVIEW

**Comment by JoshHyde9** [comment]
I think light theme tooltip looks like garbage now that I am looking at it in the PR

**Comment by JoshHyde9** [comment]
I am also not rebasing to change the name of the commit message

**Comment by maxdemaio** [comment]
GUYS LGTM SOMEONE MERGE (MR. PR MAN @Hacksore )

**Comment by nathanroark** [comment]
shout out to @JoshHyde9 for finding the .classed attr on d3 items so we can use tailwind now!

**Pull request merged**
