### PR TITLE
Initial commit

### LINKED ISSUE #30: Make tags look better
Maybe make them pills for good IMG_2724

### PR DESCRIPTION
**Pull request by zfilippos**
I asked but you did not reposd, so ill just assume this is it 

fixes #30

### CODE REVIEW

**Comment by zfilippos** [comment]
Χωρίς τίτλο

**Review by Hacksore — CHANGES_REQUESTED** [review]
@zfilippos can you make each tag separate like GitHub labels

IMG_2725

**Comment by maxdemaio** [comment]
@zfilippos, mr. pr man, 🚀, likes to sleep a lot so he probably didn't see your message

**Comment by zfilippos** [comment]
image
2nd commit
So i assume this is it. But there are in the same collor not like githubs.

**Comment by Hacksore** [comment]
The color is harsh but this is good enough, thanks for the contribution!

**Pull request merged**
